title: Quadrant Investing
description: 'A unifying framework for Quality, Growth, and Value Investing'
social_link: twitter
social_username: broccolini
github_repo: athena
github_username: broccolini
theme_color: light
remote_theme: internet-de-france/athena  #heiswayi/the-plain
baseurl: /web

# Site Settings
# url:                https://4drant.github.io # main url
# baseurl:            /web
# permalink:          /:title # Post permalink
# timezone:           Asia/Kuala_Lumpur # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
# mathjax:            true  # enables support for mathjax - set to 'false' to disable


defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - light
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
